
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
  - repo: https://github.com/psf/black
    rev: 23.12.1
    hooks:
      - id: black
        language_version: python3.12

  - repo: https://github.com/python-poetry/poetry
    rev: '1.7.0'
    hooks:
    -   id: poetry-check
    -   id: poetry-lock
    -   id: poetry-export

  - repo: https://github.com/rtts/djhtml
    rev: '3.0.6'  # replace with the latest tag on GitHub
    hooks:
      - id: djhtml
      - id: djcss
  - repo: https://github.com/PyCQA/prospector
    rev: 1.10.0
    hooks:
    -   id: prospector
    additional_dependencies:
        - ".[with-mypy,with-bandit]"
        - args: [
        '--with-tool=mypy',
        '--with-tool=bandit',
      ]
