version: "2"
services:
    nhhc:
        ports:
            - 8080:8080
        environment:
            - DOPPLER_TOKEN: ${DOPPLER_TOKEN}
            - DOPPLER_PROJECT: "nhhc"
            - DOPPLER_CONFIG: "dev"
            - DOPPLER_ENV: 1
        image: terrybrooks/nhhc
