services:
    nhhc:
        environment:
            - DOPPLER_TOKEN: "dp.st.prod.XHIp5y7f5Mc5h2Wfs7aOWKIXtDL6TXYFWBMJl5SaVVR"
            - DOPPLER_PROJECT: "nhhc"
            - DOPPLER_CONFIG: "prod"
            - DOPPLER_ENV: 1
        image: terrybrooks/nhhc-arm
        ports:
          - "80:7772"
          - "443:7772"
