services:
    nhhc:
        environment:
            - DOPPLER_TOKEN: $("DOPPLER_TOKEN")
            - DOPPLER_PROJECT: "nhhc"
            - DOPPLER_CONFIG: "prod"
            - DOPPLER_ENV: 1
        image: terrybrooks/nhhc-arm
        ports:
          - "80:7772"
          - "443:7772"
