name: General Test and Deploy - 2nd Approach
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code Checkout
        uses: 'Actions/Checkout@v3'
      - name: Fetch Env Vars From Doppler
        uses: dopplerhq/secrets-fetch-action@v1.1.3
        id: secrets
        with:
          doppler-token: ${{ secrets.DOPPLER_TOKEN }}
          inject-env-vars: true
          doppler-project: nhhc
          doppler-config: stg
      - name: Create VENV 
        run: |
          python3 -m venv .  venv
      - name: "Setup Python, Poetry and Dependencies"
        uses: packetcoders/action-setup-cache-python-poetry@main
        with:
            python-version: 3.11.4
            poetry-version: 1.5.1
            install-args: --without dev test
      - name: Run Unit Tests
        run: |
          source .venv/bin/activate
          python nhhc/manage.py test
        
  merge:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Deployw
        run: echo "Deploying Code..."
