name: General Test and Deploy 
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code Checkout
        uses: 'Actions/Checkout@v3'
      - name: Fetch Env Vars From Doppler
        uses: dopplerhq/secrets-fetch-action@v1.1.3
        id: secrets
        with:
          doppler-token: ${{ secrets.DOPPLER_TOKEN }}
          inject-env-vars: true
          doppler-project: nhhc
          doppler-config: stg
      - name: Setup Python3.12
        uses: actions/setup-python@v5
        with:
            python-version: 3.12
            cache: 'poetry'
      - name: cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          pip install --upgrade pip
          pip install poetry 
          poetry install --without dev test
      - name: Run Tests
        run: |
          source .venv/bin/activate
          python nhhc/manage.py test
          
  merge:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Deployw
        run: echo "Deploying Code"..r
