name: General Test and Deploy
on: push
permissions:
  contents: write
jobs:
  linter:
    # Reusable workflows must be referenced at the job level
    uses: terry-brooksjr/nhhc_workplace_management_system/.github/workflows/generic.yml@feat_ADDS-MAINTENCE-MODE
    with:
      doppler-project: nhhc
      doppler-config: prod
      python-version: 3.12.5
      cache-type: pip

  tests:
    # Reusable workflows must be referenced at the job level
    uses: terry-brooksjr/nhhc_workplace_management_system/.github/workflows/generic.yml@feat_ADDS-MAINTENCE-MODE
    with:
      doppler-project: nhhc
      doppler-config: prod
      python-version: 3.12.5
      cache-type: pip
