
Copy code
name: General Test and Deploy
on: push
permissions:
  contents: write
jobs:
  setup-virtualenv:
    runs-on: ubuntu-latest
    env:
      DOPPLER_TOKEN: ${{ secrets.DOPPLER_TOKEN }}
      DOPPLER_PROJECT: ${{ vars.DOPPLER_PROJECT }}
      DOPPLER_CONFIG: ${{ vars.DOPPLER_CONFIG }}
    steps:
      - name: Get Code Checkout
        uses: actions/checkout@v3
      - name: Fetch Env Vars From Doppler
        uses: dopplerhq/secrets-fetch-action@v1.1.3
        id: secrets
        with:
          doppler-token: ${{ secrets.DOPPLER_TOKEN }}
          inject-env-vars: true
          doppler-project: ${{ vars.DOPPLER_PROJECT }}
          doppler-config: ${{ vars.DOPPLER_CONFIG }}
      - uses: actions/setup-python@v4
      - uses: syphar/restore-virtualenv@v1
        id: cache-virtualenv
      - uses: syphar/restore-pip-download-cache@v1
        if: steps.cache-virtualenv.outputs.cache-hit != 'true'
      - name: Install Dependencies
        run: pip install -r requirements.txt
        if: steps.cache-virtualenv.outputs.cache-hit != 'false

  linter:
    needs: setup-virtualenv
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Fetch Env Vars From Doppler
        uses: dopplerhq/secrets-fetch-action@v1.1.3
        id: secrets
        with:
          doppler-token: ${{ secrets.DOPPLER_TOKEN }}
          inject-env-vars: true
          doppler-project: ${{ env.DOPPLER_PROJECT }}
          doppler-config: ${{ env.DOPPLER_CONFIG }}
      - uses: actions/setup-python@v4
      - uses: syphar/restore-virtualenv@v1
        id: cache-virtualenv
      - run: |
          black --check --diff . && \
          isort . --diff --check-only

  tests:
    needs: setup-virtualenv
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
      - name: Fetch Env Vars From Doppler
        uses: dopplerhq/secrets-fetch-action@v1.1.3
        id: secrets
        with:
          doppler-token: ${{ secrets.DOPPLER_TOKEN }}
          inject-env-vars: true
          doppler-project: ${{ env.DOPPLER_PROJECT }}
          doppler-config: ${{ env.DOPPLER_CONFIG }}
      - uses: syphar/restore-virtualenv@v1
        id: cache-virtualenv
      - run: |
          sudo mkdir /data && \
          sudo chown -R $USER:$USER /data && \
          sudo chmod 777 && \
          cd nhhc && \
          exit 0;