on:
  workflow_call:
    inputs:
      doppler-config:
        required: true
        type: string
      doppler-project:
        required: true
        type: string
      cache-type:
        required: true
        type: string            
      python-version:
        required: true
        type: string
    secrets: inherit

jobs:
  runs-on: ubuntu-latest
  steps:
    - name: Get Code Checkout
      uses: actions/checkout@v3
    - name: Fetch Env Vars From Doppler
      id: secret          
      uses: dopplerhq/secrets-fetch-action@v1.1.3
      with:
        doppler-token: ${{ secrets.DOPPLER_TOKEN }}
        doppler-project: ${{ inputs.doppler-project }}
        doppler-config: ${{ inputs.doppler-config }}
    - name: Set Up Correct Python Version and Cache Virtual Environment
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}
        cache: ${{ inputs.cache-type }}
    - name: Cache pip dependencies
      uses: actions/cache@v4
      id: cache
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
        ${{ runnerr.os }}-pip-
    - name: Install Dependencies
      if: steps.cache.outputs.cache-hit != true
      run: pip install -r requirements.txt
      