on:
    workflow_call:
      inputs:
        doppler-config:
          required: true
          type: string
        doppler-project:
          required: true
          type: string
        cache-type:
          required: true
          type: string            
        python-version:
          required: true
          type: string
      secrets: inherit
  
  permissions:
    contents: write
  
  jobs:
    +
    :
      runs-on: ubuntu-latest
      steps:
        - name: Get Code Checkout
          uses: actions/checkout@v3
  
        - name: Fetch Env Vars From Doppler
          uses: dopplerhq/secrets-fetch-action@v1.1.3
          id: secrets
          with:
            doppler-token: ${{ secrets.DOPPLER_TOKEN }}
            doppler-project: ${{ inputs.doppler-project }}
            doppler-config: ${{ inputs.doppler-config }}
  
        - name: Set Up Correct Python Version and Cache Virtual Environment
          uses: actions/setup-python@v5
          with:
            python-version: ${{ inputs.python-version }}
            cache: ${{ inputs.cache-type }}
  
        # Cache dependencies based on requirements.txt file
        - name: Cache pip dependencies
          uses: actions/cache@v3
          with:
            path: ~/.cache/pip
            key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
            restore-keys: |
              ${{ runner.os }}-pip-
  
        - name: Install Dependencies
          run: pip install -r requirements.txt
          on:
            workflow_call:
              inputs:
                doppler-config:
                  required: true
                  type: string
                doppler-project:
                  required: true
                  type: string
                cache-type:
                  required: true
                  type: string            
                python-version:
                  required: true
                  type: float
              secrets: inherit
          
          permissions:
            contents: write
          
          jobs:
            setup-virtualenv:
              runs-on: ubuntu-latest
              steps:
                - name: Get Code Checkout
                  uses: actions/checkout@v3
          
                - name: Fetch Env Vars From Doppler
                  uses: dopplerhq/secrets-fetch-action@v1.1.3
                  id: secrets
                  with:
                    doppler-token: ${{ secrets.DOPPLER_TOKEN }}
                    doppler-project: ${{ inputs.doppler-project }}
                    doppler-config: ${{ inputs.doppler-config }}
          
                - name: Set Up Correct Python Version and Cache Virtual Environment
                  uses: actions/setup-python@v5
                  with:
                    python-version: ${{ inputs.python-version }}
                    cache: ${{ inputs.cache-type }}
          
                # Cache dependencies based on requirements.txt file
                - name: Cache pip dependencies
                  uses: actions/cache@v3
                  with:
                    path: ~/.cache/pip
                    key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
                    restore-keys: |
                      ${{ runner.os }}-pip-
          
                - name: Install Dependencies
                  run: pip install -r requirements.txt
          